name: Bug Report
description: Something isn't working as expected
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this! Please fill out the sections below so we can help you as quickly as possible.

        **Before submitting**, please make sure you have:
        - [ ] Updated to the [latest version](https://github.com/pierr3/TrackAudio/releases) of TrackAudio
        - [ ] Checked the [Troubleshooting section](https://github.com/pierr3/TrackAudio/blob/main/README.md#troubleshooting) in the README
        - [ ] Searched [existing issues](https://github.com/pierr3/TrackAudio/issues) to see if this has already been reported

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Describe the problem you ran into. What were you doing when it happened?
      placeholder: 'e.g. I was connected as LFPG_TWR and after about 20 minutes, my transmissions stopped going through...'
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: If possible, list the steps someone would need to follow to see the same problem.
      placeholder: |
        1. Connect as ...
        2. Add frequency ...
        3. Press PTT and ...
    validations:
      required: false

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: 'e.g. I expected my transmission to go through normally'
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: TrackAudio version
      description: You can find this at the bottom of the TrackAudio window.
      placeholder: 'e.g. 1.3.3 or 1.4.0-beta.1'
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Windows 10
        - Windows 11
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux (Ubuntu/Debian)
        - Linux (Other)
    validations:
      required: true

  - type: input
    id: os-version
    attributes:
      label: OS version
      description: Your specific OS version helps us narrow down the problem.
      placeholder: 'e.g. Windows 11 24H2, macOS 15.2, Ubuntu 24.04'
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Log file
      description: |
        Please paste the contents of your log file here. You can find it at:
        - **Windows:** `%LocalAppData%\trackaudio` (paste this path in File Explorer's address bar)
        - **macOS:** `~/Library/Application Support/trackaudio`
        - **Linux:** `~/.local/state/trackaudio`
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem. You can drag and drop images here.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Anything else?
      description: Any other details that might be relevant (audio devices, controller client used, network region, etc.)
    validations:
      required: false
